#!/usr/bin/env python3
"""Build the self-contained viewer.html by inlining all viewer assets.

Source files (edit these):
  - viewer.js      — ES module class for embedding
  - viewer.css     — styles for the viewer UI
  - template.html  — HTML template for UI controls
  - static/*.jpg   — cubemap face images
  - static/draco/  — vendored Draco glTF decoder (wasm + emscripten wrapper)

Generated file (do not edit):
  - ../viewer.html — standalone file for file:// usage with everything inlined

Run from repo root:
    uv run python src/threejs_viewer/viewer/build.py
"""

import base64
import gzip
import io
import re
from pathlib import Path

VIEWER_DIR = Path(__file__).parent
OUTPUT_HTML = VIEWER_DIR.parent / "viewer.html"
STATIC_DIR = VIEWER_DIR / "static"
DRACO_DIR = STATIC_DIR / "draco"

THREE_VERSION = "0.183.2"
CUBEMAP_FACES = ["px", "nx", "py", "ny", "pz", "nz"]


def _read_cubemap_b64() -> dict:
    """Read cubemap JPEG files and return base64-encoded dict."""
    data = {}
    for face in CUBEMAP_FACES:
        jpg_path = STATIC_DIR / f"{face}.jpg"
        data[face] = base64.b64encode(jpg_path.read_bytes()).decode("ascii")
    return data


def _gzip_b64(raw: bytes) -> str:
    """Deterministically gzip + base64 a blob (mtime=0 so rebuilds are stable)."""
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(raw)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def _read_draco_b64() -> dict:
    """Read the vendored Draco glTF decoder and return gzip+base64 payloads.

    Raw is ~251 KB (wasm 188 KB + wrapper 57 KB); gzip+base64 is ~100 KB, so
    the decoder costs ~15% of viewer.html rather than ~49%. The viewer inflates
    both with DecompressionStream('gzip') before handing them to DRACOLoader.
    """
    return {
        "wasm": _gzip_b64((DRACO_DIR / "draco_decoder.wasm").read_bytes()),
        "wrapper": _gzip_b64((DRACO_DIR / "draco_wasm_wrapper.js").read_bytes()),
    }


def build():
    js_content = (VIEWER_DIR / "viewer.js").read_text(encoding="utf-8")
    controls_content = (VIEWER_DIR / "controls.js").read_text(encoding="utf-8")
    css_content = (VIEWER_DIR / "viewer.css").read_text(encoding="utf-8")
    html_template = (VIEWER_DIR / "template.html").read_text(encoding="utf-8")
    cubemap_data = _read_cubemap_b64()
    draco_data = _read_draco_b64()

    # Strip the local controls.js import from viewer.js (we inline it instead).
    js_content = re.sub(
        r"^\s*import\s+\{\s*ViewerControls\s*\}\s+from\s+['\"]\./controls\.js['\"];?\s*$\n?",
        "",
        js_content,
        count=1,
        flags=re.MULTILINE,
    )

    # Strip the `export { ... }` line from controls.js so it inlines as plain code.
    controls_inlined = re.sub(
        r"^\s*export\s*\{[^}]*\};?\s*$\n?",
        "",
        controls_content,
        flags=re.MULTILINE,
    )
    # Also drop its `import * as THREE from 'three';` — the outer module already imports THREE.
    controls_inlined = re.sub(
        r"^\s*import\s+\*\s+as\s+THREE\s+from\s+['\"]three['\"];?\s*$\n?",
        "",
        controls_inlined,
        count=1,
        flags=re.MULTILINE,
    )

    # Remove the 'export' keyword from 'export class ThreeJSViewer'
    js_inlined = re.sub(
        r"^export class ", "class ", js_content, count=1, flags=re.MULTILINE
    )

    # Prepend controls.js source so ViewerControls is in scope when ThreeJSViewer runs.
    js_inlined = controls_inlined + "\n" + js_inlined

    # Build the cubemap data as a JS object literal
    cubemap_js_entries = []
    for face in CUBEMAP_FACES:
        cubemap_js_entries.append(f"    {face}: '{cubemap_data[face]}'")
    cubemap_js = "const CUBEMAP_DATA = {\n" + ",\n".join(cubemap_js_entries) + "\n};"

    # Draco glTF decoder, gzip+base64 (inflated in the browser before use).
    draco_js = (
        "const DRACO_DECODER_DATA = {\n"
        f"    wasmGzB64: '{draco_data['wasm']}',\n"
        f"    wrapperGzB64: '{draco_data['wrapper']}'\n"
        "};"
    )

    # Escape backticks and ${} in template for JS template literal
    html_escaped = (
        html_template.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    )
    template_js = f"const HTML_TEMPLATE = `{html_escaped}`;"

    # Indent CSS for the <style> block
    css_indented = "\n".join(
        "        " + line if line.strip() else "" for line in css_content.splitlines()
    )

    html = f"""\
<!-- DO NOT EDIT — this file is generated by viewer/build.py from the source files in viewer/ -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Three.js Viewer</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        html, body {{ width: 100%; height: 100%; overflow: hidden; }}
        #viewer-container {{ width: 100%; height: 100%; }}
{css_indented}
    </style>
    <script type="importmap">
    {{
        "imports": {{
            "three": "https://unpkg.com/three@{THREE_VERSION}/build/three.module.js",
            "three/addons/": "https://unpkg.com/three@{THREE_VERSION}/examples/jsm/"
        }}
    }}
    </script>
</head>
<body>
    <div id="viewer-container"></div>
    <script type="module">
{cubemap_js}

{draco_js}

{template_js}

{js_inlined}

// Standalone instantiation
const container = document.getElementById('viewer-container');
window.threejsViewer = new ThreeJSViewer(container, {{
    htmlTemplate: HTML_TEMPLATE,
    cubemapData: CUBEMAP_DATA,
    dracoDecoder: DRACO_DECODER_DATA
}});
    </script>
</body>
</html>
"""
    OUTPUT_HTML.write_text(html, encoding="utf-8", newline="\n")
    print(f"Built {OUTPUT_HTML} ({len(html)} bytes)")


if __name__ == "__main__":
    build()
