#!/usr/bin/env python3
"""Build the self-contained viewer.html by inlining all viewer assets.

Source files (edit these):
  - viewer.js      — ES module class for embedding
  - viewer.css     — styles for the viewer UI
  - template.html  — HTML template for UI controls
  - static/*.jpg   — cubemap face images

Generated file (do not edit):
  - ../viewer.html — standalone file for file:// usage with everything inlined

Run from repo root:
    uv run python src/threejs_viewer/viewer/build.py
"""

import base64
import re
from pathlib import Path

VIEWER_DIR = Path(__file__).parent
OUTPUT_HTML = VIEWER_DIR.parent / "viewer.html"
STATIC_DIR = VIEWER_DIR / "static"

THREE_VERSION = "0.183.2"
CUBEMAP_FACES = ["px", "nx", "py", "ny", "pz", "nz"]


def _read_cubemap_b64() -> dict:
    """Read cubemap JPEG files and return base64-encoded dict."""
    data = {}
    for face in CUBEMAP_FACES:
        jpg_path = STATIC_DIR / f"{face}.jpg"
        data[face] = base64.b64encode(jpg_path.read_bytes()).decode("ascii")
    return data


def build():
    js_content = (VIEWER_DIR / "viewer.js").read_text(encoding="utf-8")
    css_content = (VIEWER_DIR / "viewer.css").read_text(encoding="utf-8")
    html_template = (VIEWER_DIR / "template.html").read_text(encoding="utf-8")
    cubemap_data = _read_cubemap_b64()

    # Remove the 'export' keyword from 'export class ThreeJSViewer'
    js_inlined = re.sub(
        r"^export class ", "class ", js_content, count=1, flags=re.MULTILINE
    )

    # Build the cubemap data as a JS object literal
    cubemap_js_entries = []
    for face in CUBEMAP_FACES:
        cubemap_js_entries.append(f"    {face}: '{cubemap_data[face]}'")
    cubemap_js = "const CUBEMAP_DATA = {\n" + ",\n".join(cubemap_js_entries) + "\n};"

    # Escape backticks and ${} in template for JS template literal
    html_escaped = (
        html_template.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    )
    template_js = f"const HTML_TEMPLATE = `{html_escaped}`;"

    # Indent CSS for the <style> block
    css_indented = "\n".join(
        "        " + line if line.strip() else "" for line in css_content.splitlines()
    )

    html = f"""\
<!-- DO NOT EDIT — this file is generated by viewer/build.py from the source files in viewer/ -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Three.js Viewer</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        html, body {{ width: 100%; height: 100%; overflow: hidden; }}
        #viewer-container {{ width: 100%; height: 100%; }}
{css_indented}
    </style>
    <script type="importmap">
    {{
        "imports": {{
            "three": "https://unpkg.com/three@{THREE_VERSION}/build/three.module.js",
            "three/addons/": "https://unpkg.com/three@{THREE_VERSION}/examples/jsm/"
        }}
    }}
    </script>
</head>
<body>
    <div id="viewer-container"></div>
    <script type="module">
{cubemap_js}

{template_js}

{js_inlined}

// Standalone instantiation
const container = document.getElementById('viewer-container');
window['threejs-viewer'] = new ThreeJSViewer(container, {{
    htmlTemplate: HTML_TEMPLATE,
    cubemapData: CUBEMAP_DATA
}});
    </script>
</body>
</html>
"""
    OUTPUT_HTML.write_text(html, encoding="utf-8", newline="\n")
    print(f"Built {OUTPUT_HTML} ({len(html)} bytes)")


if __name__ == "__main__":
    build()
